//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorLibrary
    {
        public int id { get; set; }
        public int BookID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public int YearOfBirth { get; set; }
    
        public virtual BookLibrary BookLibrary { get; set; }
    }
}
