//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookLibrary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookLibrary()
        {
            this.AuthorLibrary = new HashSet<AuthorLibrary>();
            this.PersonLibrary = new HashSet<PersonLibrary>();
        }
    
        public int UniqueID { get; set; }
        public string Book { get; set; }
        public string Author { get; set; }
        public int Pages { get; set; }
        public int RealeseDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorLibrary> AuthorLibrary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonLibrary> PersonLibrary { get; set; }
    }
}
