//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonLibrary
    {
        public int id { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<System.DateTime> RentedFrom { get; set; }
        public string RentedTo { get; set; }
        public string Name { get; set; }
        public long IDNumber { get; set; }
        public long EGN { get; set; }
        public string Adress { get; set; }
        public string Gender { get; set; }
        public long Phone { get; set; }
        public string email { get; set; }
    
        public virtual BookLibrary BookLibrary { get; set; }
    }
}
